/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type ListRequest = {
  accountId: string;
  billingPeriodId: string;
  enrichData?: boolean;
  entryType?: types.GetAccountsAccountIdBillingPeriodsBillingPeriodIdTransactionsEntryTypeEnum;
  filterType?: types.GetAccountsAccountIdBillingPeriodsBillingPeriodIdTransactionsFilterTypeEnum;
  skip?: number;
  top?: number;
  contextTenantid: string;
};
