/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  accountId: string;
  hasStatement?: boolean;
  linkedAccount?: boolean;
  contextTenantid: string;
};

export type GetRequest = {
  accountId: string;
  billingPeriodId: string;
  contextTenantid: string;
};
