/**
 * File Generated by Sideko (sideko.dev)
 */

import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "new-day-ts/core";
import * as requests from "new-day-ts/resources/accounts/billing-periods/spend-types/request-types";
import * as types from "new-day-ts/types";

export class SpendTypesClient extends CoreResourceClient {
  constructor(client: CoreClient) {
    super(client);
  }

  /**
   * Shows billing period breakdown per spend type.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<
    | types.GetBillingPeriodSpendTypesResponse
    | types.GetBillingPeriodSpendTypesResponse
    | types.GetBillingPeriodSpendTypesResponse
  > {
    return this._client.makeRequest({
      method: "get",
      path: `/accounts/${request.accountId}/billing-periods/${request.billingPeriodId}/spend-types`,
      headers: { "context-tenantid": request.contextTenantid },
      responseType: "json",
      opts,
    });
  }
}
