/**
 * File Generated by Sideko (sideko.dev)
 */

import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "new-day-ts/core";
import * as requests from "new-day-ts/resources/accounts/dues/arrears/request-types";
import * as types from "new-day-ts/types";

export class ArrearsClient extends CoreResourceClient {
  constructor(client: CoreClient) {
    super(client);
  }

  /**
 * import Client from "new-day-ts";

const client = new Client();

const res = await client.accounts.dues.arrears.list({
  accountId: "string",
  contextTenantid: "string",
});
 */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<
    | types.GetAccountArrearsResponse
    | types.GetAccountArrearsResponse
    | types.GetAccountArrearsResponse
  > {
    return this._client.makeRequest({
      method: "get",
      path: `/accounts/${request.accountId}/dues/arrears`,
      headers: { "context-tenantid": request.contextTenantid },
      responseType: "json",
      opts,
    });
  }
}
