/**
 * File Generated by Sideko (sideko.dev)
 */

import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "new-day-ts/core";
import * as requests from "new-day-ts/resources/accounts/billing-periods/current/transactions/request-types";
import * as types from "new-day-ts/types";
import qs from "qs";

export class TransactionsClient extends CoreResourceClient {
  constructor(client: CoreClient) {
    super(client);
  }

  /**
   * Lists the transactions for the current billing period.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<
    | types.GetBillingPeriodTransactionsResponse
    | types.GetBillingPeriodTransactionsResponse
    | types.GetBillingPeriodTransactionsResponse
  > {
    return this._client.makeRequest({
      method: "get",
      path: `/accounts/${request.accountId}/billing-periods/current/transactions`,
      query: [
        qs.stringify({ enrichData: request.enrichData }),
        qs.stringify({ entryType: request.entryType }),
        qs.stringify({ filterType: request.filterType }),
        qs.stringify({ skip: request.skip }),
        qs.stringify({ top: request.top }),
      ],
      headers: { "context-tenantid": request.contextTenantid },
      responseType: "json",
      opts,
    });
  }
}
