/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type AccountArrearsBreakdown = {
  /**
   * Indicator showing how many cycles in arrears the balance is
   */
  age?: number;
  amount?: types.Amount;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | number
    | undefined
    | types.Amount
    | any;
};
