/**
 * File Generated by Sideko (sideko.dev)
 */

export enum AccountStatusTypeEnum {
  AuthorisationBlocked = "AuthorisationBlocked",
  DebtSold = "DebtSold",
  OverLimit = "OverLimit",
  PastDue = "PastDue",
}
