/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type AccountSpendType = {
  /**
   * Date when the spend type entry was created for the account
   */
  createdAt?: string | null;
  /**
   * Details of non-statemented balance components on the account
   */
  currentCycleBalances?: types.CycleBalances[] | null;
  currentRates?: types.CurrentRates;
  /**
   * This will contain either the offer description or the merchant name where the transaction occurred
   */
  description?: string | null;
  /**
   * Date of first debit for this spend type
   */
  firstDebitAt?: string | null;
  gotoRates?: types.GotoRates;
  /**
   * Spend Type unique identifier
   */
  id?: string | null;
  instalment?: types.Instalment;
  /**
   * Spend Type Name (e.g. Purchase, Cash, Instalment etc.)
   */
  name?: string | null;
  /**
   * Previous type of the payment plan, populated if applicable (e.g. Instalment)
   */
  previousType?: string | null;
  /**
   * Details of statemented balance components on the account
   */
  priorCycleBalances?: types.CycleBalances[] | null;
  totalBalance?: types.Amount;
  /**
   * Type of the payment plan
   */
  type?: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | types.CycleBalances[]
    | undefined
    | types.CurrentRates
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | types.GotoRates
    | undefined
    | null
    | string
    | undefined
    | types.Instalment
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | types.CycleBalances[]
    | undefined
    | types.Amount
    | undefined
    | string
    | any;
};
