/**
 * File Generated by Sideko (sideko.dev)
 */

export type Address = {
  /**
   * City Name
   */
  city?: string;
  /**
   * Country Code ISO Alpha 2 or Alpha 3
   */
  countryCode?: string;
  /**
   * Country Name
   */
  countryName?: string;
  /**
   * Country Sub Division Code
   */
  countrySubdivisionCode?: string;
  /**
   * Address line 1
   */
  line1?: string;
  /**
   * Address line 2
   */
  line2?: string;
  /**
   * Postal Code
   */
  postalCode?: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | any;
};
