/**
 * File Generated by Sideko (sideko.dev)
 */

export type Amount = {
  /**
   * Currency code of the value (ISO 4217 alpha-3 format)
   */
  currencyCode?: string | null;
  /**
   * Amount Value
   */
  value?: number | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | number
    | any;
};
