/**
 * File Generated by Sideko (sideko.dev)
 */

export type AuthorisationInstrument = {
  /**
   * First Six Digits of the Card number, if applicable
   */
  firstSixDigits?: string | null;
  /**
   * Last four Digits of the Card number, if applicable
   */
  lastFourDigits?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
