/**
 * File Generated by Sideko (sideko.dev)
 */

export type BillingPeriod = {
  /**
   * Account identifier of the billing period, to be used in subsequent calls for the given billing period
   */
  accountId?: string | null;
  /**
   * End Date for the billing period
   */
  endDate?: string;
  /**
   * Has not-suppressed statement for the billing period
   */
  hasStatement?: boolean | null;
  /**
   * Billing Period Identifier
   */
  id?: string;
  /**
   * &gt;Start Date for the billing period
   */
  startDate?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | string
    | undefined
    | null
    | boolean
    | undefined
    | string
    | undefined
    | null
    | string
    | any;
};
