/**
 * File Generated by Sideko (sideko.dev)
 */

export type BoostedPayment = {
  /**
   * Currency code of the due value
   */
  currencyCode?: string | null;
  /**
   * Absolute value of the difference between the agreed minimum payment and the boosted amount
   */
  delta?: number;
  /**
   * Absolute value of the boosted amount
   */
  value?: number | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | number
    | undefined
    | null
    | number
    | any;
};
