/**
 * File Generated by Sideko (sideko.dev)
 */

export type CreditLimitIncreasePreference = {
  /**
   * selected by Customer (Optin, Optout, Exclude)
   */
  option?: string | null;
  /**
   * Last date when option was updated
   */
  updateAt?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
