/**
 * File Generated by Sideko (sideko.dev)
 */

export enum CreditReleaseTypeEnum {
  CreditReleaseDelayed = "CreditReleaseDelayed",
  CreditReleaseImmediate = "CreditReleaseImmediate",
  CreditReleased = "CreditReleased",
}
