/**
 * File Generated by Sideko (sideko.dev)
 */

export type CreditLimit = {
  /**
   * The currency code of the credit limit
   */
  currencyCode?: string;
  /**
   * Credit Limit type (&quot;Account&quot; or &quot;Cash&quot;)
   */
  type?: string;
  /**
   * The value of the credit limit for given type
   */
  value?: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | any;
};
