/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type CycleBalances = {
  amount?: types.Amount;
  /**
   * Type of balance, e.g. Principal, Interest, Fee
   */
  balanceType?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | types.Amount
    | undefined
    | null
    | string
    | any;
};
