/**
 * File Generated by Sideko (sideko.dev)
 */

export type Delinquency = {
  /**
   * Delinquency level of the account
   */
  age?: number | null;
  /**
   * Indicates if the account is delinquent
   */
  isDelinquent?: boolean;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | number
    | undefined
    | boolean
    | any;
};
