/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type EnrichmentData = {
  merchantResult?: types.MerchantResult;
  purchaseReceipt?: types.PurchaseReceipt;
  resultStatus?: types.ResultStatus;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | types.MerchantResult
    | undefined
    | types.PurchaseReceipt
    | undefined
    | types.ResultStatus
    | any;
};
