/**
 * File Generated by Sideko (sideko.dev)
 */

export type ForeignAmount = {
  /**
   * Currency code of the value (ISO 4217 standard - Alpha 3)
   */
  currencyCode?: string | null;
  /**
   * Exchange rate from Foreign to Account&#x27;s billing currency
   */
  exchangeRate?: number | null;
  /**
   * Signed value of the transaction amount (for foreign spend transactions)
   */
  value?: number | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | number
    | undefined
    | null
    | number
    | any;
};
