/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type GetAccountDuesResponse = {
  /**
   * Alternate minimum payment due details
   */
  alternateMinimumDues?: types.AlternateMinimumDue[] | null;
  boostedPayment?: types.BoostedPayment;
  current?: types.Amount;
  delinquency?: types.Delinquency;
  lastPayment?: types.LastPayment;
  /**
   * Next Statement date selected for the account
   */
  nextStatementDate?: string | null;
  /**
   * Payment due date for the most recent closed billing period
   */
  paymentDueDate?: string | null;
  paymentRequested?: types.Amount;
  recommendedExtraPayment?: types.RecommendedExtraPayment;
  total?: types.Amount;
  totalArrears?: types.Amount;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | types.AlternateMinimumDue[]
    | undefined
    | types.BoostedPayment
    | undefined
    | types.Amount
    | undefined
    | types.Delinquency
    | undefined
    | types.LastPayment
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | types.Amount
    | undefined
    | types.RecommendedExtraPayment
    | undefined
    | types.Amount
    | undefined
    | types.Amount
    | any;
};
