/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type GetAccountSpendTypesResponse = {
  /**
   * Spend Type breakdown applicable for the given account and billing Period
   */
  value?: types.AccountSpendType[];

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: undefined | types.AccountSpendType[] | any;
};
