/**
 * File Generated by Sideko (sideko.dev)
 */

export enum GetAccountsAccountIdTransactionsFilterTypeEnum {
  All = "All",
  Fee = "Fee",
  FeeAndInterest = "FeeAndInterest",
  IncludeInternalTransactions = "IncludeInternalTransactions",
  Interest = "Interest",
  PaymentCredits = "PaymentCredits",
  Recurring = "Recurring",
}
