/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type GetBillingPeriodsResponse = {
  /**
   * Collection of Billing Periods (Statement dates)
   */
  value?: types.BillingPeriod[];

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: undefined | types.BillingPeriod[] | any;
};
