/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type GetBillingPeriodDetailsResponse = {
  arrearsDue?: types.Amount;
  /**
   * Collection of available credit limits
   */
  availableLimit?: types.CreditLimit[];
  closingBalance?: types.Amount;
  /**
   * Collection of customer credit limits
   */
  creditLimit?: types.CreditLimit[];
  estimatedInterest?: types.Amount;
  interestAmount?: types.Amount;
  openingBalance?: types.Amount;
  /**
   * Type of payment due (Current)
   */
  paymentDue?: types.PaymentDue[];
  /**
   * Payment due date for the billing period
   */
  paymentDueDate?: string | null;
  plannedRegularPayment?: types.Amount;
  /**
   * Date of the last billing period
   */
  previousBillingPeriodEndDate?: string | null;
  /**
   * Collection of Spend Types
   */
  spendTypes?: types.SpendType[];
  totalCredits?: types.Amount;
  totalDebits?: types.Amount;
  totalDue?: types.Amount;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | types.Amount
    | undefined
    | types.CreditLimit[]
    | undefined
    | types.Amount
    | undefined
    | types.CreditLimit[]
    | undefined
    | types.Amount
    | undefined
    | types.Amount
    | undefined
    | types.Amount
    | undefined
    | types.PaymentDue[]
    | undefined
    | null
    | string
    | undefined
    | types.Amount
    | undefined
    | null
    | string
    | undefined
    | types.SpendType[]
    | undefined
    | types.Amount
    | undefined
    | types.Amount
    | undefined
    | types.Amount
    | any;
};
