/**
 * File Generated by Sideko (sideko.dev)
 */

export type GetAccountInterestRatesResponse = {
  /**
   * Annual Effective Rate on the account
   */
  aer?: number;
  /**
   * Annual Effective Rate on the default instalment plan
   */
  instalmentAer?: number | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | number
    | undefined
    | null
    | number
    | any;
};
