/**
 * File Generated by Sideko (sideko.dev)
 */

export type GotoRates = {
  /**
   * Annual Equivalent Rate that this SpendType will move to once the current rate expires
   */
  annualEquivalentRate?: number | null;
  /**
   * Annual interest rate that this SpendType will move to once the current rate expires
   */
  annualInterestRate?: number | null;
  /**
   * Monthly interest rate that this SpendType will move to once the current rate expires
   */
  monthlyInterestRate?: number | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | number
    | undefined
    | null
    | number
    | undefined
    | null
    | number
    | any;
};
