/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type Instalment = {
  amount?: types.Amount;
  initialAmount?: types.Amount;
  /**
   * Original term of the instalment
   */
  originalTerm?: number;
  /**
   * Remaining term of the instalment
   */
  remainingTerm?: number;
  status?: types.InstalmentStatus;
  unpaidAmount?: types.Amount;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | types.Amount
    | undefined
    | types.Amount
    | undefined
    | number
    | undefined
    | number
    | undefined
    | types.InstalmentStatus
    | undefined
    | types.Amount
    | any;
};
