/**
 * File Generated by Sideko (sideko.dev)
 */

export type InstalmentStatus = {
  /**
   * Reason of the status value, if cancelled
   */
  reason?: string | null;
  /**
   * Status value (e.g. Active, Cancelled, Complete)
   */
  value?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
