/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type LastPayment = {
  amount?: types.Amount;
  /**
   * Effective date of the last payment
   */
  createdAt?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | types.Amount
    | undefined
    | null
    | string
    | any;
};
