/**
 * File Generated by Sideko (sideko.dev)
 */

export type LinkedAccount = {
  /**
   * Account Identifier
   */
  accountId?: string | null;
  /**
   * Indicates if this is transferred to or from account
   */
  linkType?: string | null;
  /**
   * Account link or transfer date
   */
  linkedAt?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
