/**
 * File Generated by Sideko (sideko.dev)
 */

export type Logo = {
  /**
   * Logo Description
   */
  altTextTag?: string;
  /**
   * Logo Height e.g. 200, 400
   */
  height?: number;
  /**
   * Logo Type (Merchant etc.)
   */
  type?: string;
  /**
   * URL for the Logo Image
   */
  url?: string;
  /**
   * Logo Width e.g. 200, 400
   */
  width?: number;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | number
    | undefined
    | string
    | undefined
    | string
    | undefined
    | number
    | any;
};
