/**
 * File Generated by Sideko (sideko.dev)
 */

export type MerchantCategory = {
  /**
   * Category Code
   */
  code?: string;
  /**
   * Category Description
   */
  description?: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: undefined | string | undefined | string | any;
};
