/**
 * File Generated by Sideko (sideko.dev)
 */

export type MerchantLocation = {
  /**
   * &gt;Location Coordinates - Latitude
   */
  latitude?: string;
  /**
   * Location Coordinates - Longitude
   */
  longitude?: string;
  /**
   * Location Type
   */
  type?: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | any;
};
