/**
 * File Generated by Sideko (sideko.dev)
 */

export type PaymentDue = {
  /**
   * Currency code of the value
   */
  currencyCode?: string;
  /**
   * Type of payment due (&quot;Current&quot;)
   */
  type?: string;
  /**
   * Value of the payment due
   */
  value?: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | any;
};
