/**
 * File Generated by Sideko (sideko.dev)
 */

export type RecommendedExtraPayment = {
  /**
   * Currency code of the due value
   */
  currencyCode?: string | null;
  /**
   * Indicates whether the account is opted in to recommended extra payments
   */
  option?: string | null;
  /**
   * Reason for the extra payment (OverLimit or PersistentDebt)
   */
  reason?: string | null;
  /**
   * Absolute value of the extra payment requested to avoid persistent debt
   */
  value?: number | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | number
    | any;
};
