/**
 * File Generated by Sideko (sideko.dev)
 */

export type Status = {
  /**
   * Reason for the Declined status
   */
  reason?: string | null;
  /**
   * Status value (&quot;Pending&quot; or &quot;Declined&quot;)
   */
  value?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
