/**
 * File Generated by Sideko (sideko.dev)
 */

export type SubTreatment = {
  /**
   * Expected End date of the treatment
   */
  expiresAt?: string | null;
  /**
   * Unique Identifier for account treatment or workitem
   */
  id?: string | null;
  /**
   * Treatment or workitem Name
   */
  name?: string | null;
  /**
   * Owner Domain entity for the treatment
   */
  owner?: string | null;
  /**
   * Expected Start date of the treatment
   */
  startsAt?: string | null;
  /**
   * Last change date to the status of treatment
   */
  updatedAt?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
