/**
 * File Generated by Sideko (sideko.dev)
 */

export type ThreeDSecure = {
  /**
   * Mastercard supplied ACS Outcome
   */
  acsOutcome?: string | null;
  /**
   * Mastercard supplied UCAF data collection indicator
   */
  ucafCollectionIndicator?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
