/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type Transaction = {
  /**
   * Account Identifier for the transaction
   */
  accountId?: string | null;
  /**
   * Acquirer Reference Number
   */
  acquirerReferenceNumber?: string | null;
  amount?: types.Amount;
  /**
   * Authorisation Code for the approved authorisation (ISO 8583 standard)
   */
  authorisationCode?: string | null;
  /**
   * Balance Movement Type (e.g. &quot;Purchase&quot;, &quot;Interest&quot; etc.)
   */
  balanceMovementType?: string | null;
  /**
   * Date the transaction took plac
   */
  createdAt?: string | null;
  creditRelease?: types.CreditReleaseTypeEnum;
  /**
   * Transaction Description including Merchant name Location
   */
  description?: string | null;
  enrichmentData?: types.EnrichmentData;
  /**
   * Indicates entry type of transaction (&quot;Debit&quot;, &quot;Credit&quot;)
   */
  entryType?: types.TransactionEntryTypeEnum | null;
  /**
   * Flags attributes to indicate transaction additional properties (Recurring, Cashback, DirectDebit)
   */
  flags?: string[] | null;
  foreignCurrencyAmount?: types.ForeignAmount;
  /**
   * Transaction Identifier / reference number
   */
  id?: string | null;
  instrument?: types.TransactionInstrument;
  merchant?: types.Merchant;
  /**
   * Represents Point of Service (POS) entry mode identifier of the authorisation (ISO 8583 standard)
   */
  posEntryMode?: string | null;
  /**
   * Represents Point of Service (POS) entry mode description of the authorisation (ISO 8583 standard)
   */
  posEntryModeDescription?: string | null;
  /**
   * Date the transaction posted to the account
   */
  postedAt?: string | null;
  spendType?: types.TransactionSpendType;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | types.Amount
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | types.CreditReleaseTypeEnum
    | undefined
    | null
    | string
    | undefined
    | types.EnrichmentData
    | undefined
    | null
    | types.TransactionEntryTypeEnum
    | undefined
    | null
    | string[]
    | undefined
    | types.ForeignAmount
    | undefined
    | null
    | string
    | undefined
    | types.TransactionInstrument
    | undefined
    | types.Merchant
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | undefined
    | types.TransactionSpendType
    | any;
};
