/**
 * File Generated by Sideko (sideko.dev)
 */

export type TransactionSpendType = {
  /**
   * Spend Type identifier (e.g. &quot;Plan Number - Plan Seq&quot;)
   */
  id?: string | null;
  /**
   * Spend Type Name (e.g. Purchase, Cash, Instalment etc.)
   */
  name?: string | null;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | null
    | string
    | any;
};
