/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "new-day-ts/types";

export type TransactionsSearchResponse = {
  /**
   * Indicates the next page of results
   */
  "@nextLink"?: string | null;
  /**
   * Collection of transactions
   */
  value?: types.Transaction[];

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | null
    | string
    | undefined
    | types.Transaction[]
    | any;
};
