/**
 * File Generated by Sideko (sideko.dev)
 */

import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "new-day-ts/core";
import * as requests from "new-day-ts/resources/accounts/positions/request-types";
import * as types from "new-day-ts/types";

export class PositionsClient extends CoreResourceClient {
  constructor(client: CoreClient) {
    super(client);
  }

  /**
   * Composite resource to return standard account details along with available limits, balances and dues.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<
    | types.GetAccountPositionsResponse
    | types.GetAccountPositionsResponse
    | types.GetAccountPositionsResponse
  > {
    return this._client.makeRequest({
      method: "get",
      path: `/accounts/${request.accountId}/positions`,
      headers: { "context-tenantid": request.contextTenantid },
      responseType: "json",
      opts,
    });
  }
}
