/**
 * File Generated by Sideko (sideko.dev)
 */

import { CoreResourceClient, CoreClient } from "new-day-ts/core";
import { TransactionsClient } from "new-day-ts/resources/accounts/billing-periods/current/transactions";

export class CurrentClient extends CoreResourceClient {
  transactions: TransactionsClient;

  constructor(client: CoreClient) {
    super(client);

    this.transactions = new TransactionsClient(this._client);
  }
}
