/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  accountId: string;
  enrichData?: boolean;
  skip?: number;
  status?: string;
  top?: number;
  contextTenantid: string;
};
