/**
 * File Generated by Sideko (sideko.dev)
 */

import { CoreClient } from "new-day-ts/core";
import { Environment } from "new-day-ts/environment";
import { AccountsClient } from "new-day-ts/resources/accounts";

export interface ClientOptions {
  baseUrl?: string;
  environment?: Environment;
  timeout?: number;
}

export class Client {
  protected _client: CoreClient;
  accounts: AccountsClient;

  constructor(opts?: ClientOptions) {
    const baseUrl = opts?.baseUrl
      ? opts?.baseUrl
      : opts?.environment ?? Environment.Default;
    this._client = new CoreClient({ baseUrl, timeout: opts?.timeout });

    this.accounts = new AccountsClient(this._client);
  }
}
