/**
 * File Generated by Sideko (sideko.dev)
 */

export enum Environment {
  Default = "https://dapi.stg-newdaytechnology.net/account-service",
  Server1 = "https://dapi.newdaytechnology.net/account-service",
}
